### ISSUE TITLE
DimeloChatInputAccessoryView not completely visible

### ISSUE THREAD

**Issue by maresc-g** [dimelo/Dimelo-iOS#1]
Hi,

I am trying to add the dimelo SDK on my iOS app but I have a problem with the input bar not being completely visible as you can see on this screenshot.
![image](https://cloud.githubusercontent.com/assets/4205075/14274515/1ef51582-fb12-11e5-8d11-881c9eec6ded.png)

I have this problem on every simulator I tried (from 4s to 6s plus) and with iOS 8 and 9.
I tried the dimelo sample app and it works so I think it may have something to do with the fact that I had to upgrade the deployment target from 6.1 to 8.0 when I added the dimelo SDK.
Although I saw in the DimeloChatInputAccessory.xib that there is a constraint on Toolbar.Bottom set to -32 maybe this has something to do with my problem ?
The rest of my application is working fine.

Thanks

**Comment by elhu** [comment]
Thank you for reporting this issue.
Out of curiosity, does it also happen on an actual device, or simply in the simulator?

We'll try to reproduce the issue and get back to you.

**Comment by elhu** [comment]
Just to be sure: when you experience the issue, are you using 6.1 or 8.0 as your deployment target?

**Comment by maresc-g** [comment]
I can't run it on a device right now i'll tell you if it works when I can.
I am using 8.0 as my deployment target.

**Comment by elhu** [comment]
I've checked on two different apps, with both 6.1 and 8.0 as development target, on simulators ranging from the iPhone 4s to 6s, and could not replicate the issue.

All I can think of is that there is a constraint in your app's xib somewhere that causes the issue, but it's hard to tell you more.

How are you displaying the `chatViewController`? Modally, in popover or in a `UITabBarController`?

**Comment by maresc-g** [comment]
Sorry I couldn't respond earlier I was busy working on something else.
This is what I have in dimeloDisplayChatViewController :

``` objective-c
    UIViewController* vc = [dimelo chatViewController];
    vc.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(closeChat:)];
    [self.window.rootViewController presentViewController:vc animated:YES completion:nil];
```
