### ISSUE TITLE
Impossible de faire fonctionner Dimelo en plaçant Dimelo.framework ailleurs que dans le Bundle.main

### ISSUE THREAD

**Issue by sdc-78** [dimelo/Dimelo-iOS#11]
Afin de faciliter l'intégration de Dimelo dans plusieurs applications, j'ai placé Dimelo.framework dans un pod à moi, qui est inclus dans mes applications. En faisant ainsi, la fenêtre de chat fonctionne, les assets graphiques sont bien affichés... mais les notifications ne fonctionnent plus. Pour que ça fonctionne, je suis obligé de placer Dimelo.framework directement dans le Bundle.main de chacune de mes applications, ce qui complique sérieusement leur maintenance.

**Comment by jarthod** [comment]
Nous sommes en train de regarder mais a priori il serait préférable d'utiliser notre pod et de le mettre en dépendance du votre pour ce genre de manipulation, pouvez-vous essayer ça ?

**Comment by sdc-78** [comment]
C'est la première chose que j'ai essayé. Mon application est écrite en Swift. Votre pod ne fonctionne pas dans ce cas-là..

**Comment by sdc-78** [comment]
En utilisant une version suffisamment récente de CocoaPods (1.3.0.rc.1), Dimelo semble désormais fonctionner correctement en plaçant Dimelo.framework dans un pod à moi.

**Comment by jarthod** [comment]
Ok top !
