### ISSUE TITLE
Apple binary validation fails when using Dimelo SDK 1.7.0+

### ISSUE THREAD

**Issue by anthonynevo** [dimelo/Dimelo-iOS#14]
Hello,

we uploaded our binary to iTunes Connect but we received the following error message:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "xyz". To process your delivery, the following issues must be corrected:
> 
> Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

We checked our workspace and Dimelo is the only framework which contains "iPhoneSimulator" in its Info.plist file.

By changing the value of this key to "iPhoneOS", I was able to have the binary validated by Apple but it's now a satisfactory solution.

Can you change your Info.plist as I believe we are not the only ones impacted ?

Thanks very much,
Anthony

**Comment by jarthod** [comment]
Hello @anthonynevo 

Thank you for reporting this, we have acknowledged this issue and are currently fixing it.
You can expect a new release very soon.

**Comment by waelba** [comment]
Hello @anthonynevo 

You can test with the fix `1.7.5`

**Comment by anthonynevo** [comment]
Thanks @waelbenabdallah 

It works fine now. The binary passed the Apple automatic validation process.
You can close this issue !
