### ISSUE TITLE
Error localization problem

### ISSUE THREAD

**Issue by leonovvalentin** [dimelo/Dimelo-iOS#18]
Hello!

We have a problem with error alert localization (see attach).
As temporary solution we use "Error" and "Could not send the message" string keys. But it is not documented.

Could you add documentation for this case and cases like this? It would be good if you make new string keys with prefix like "dimelo...".

![dimelo error localization](https://user-images.githubusercontent.com/1362846/35842623-e06f4b80-0b35-11e8-88ee-618f0cc751e9.png)

**Comment by waelba** [comment]
Hi @leonovvalentin,

This will be fixed in the next release (v1.7.8)

I'll update this ticket to let you know as soon as we release the new version :)

**Comment by waelba** [comment]
Hi @leonovvalentin ,
It's fixed in `v1.7.8`
Thanks

**Comment by leonovvalentin** [comment]
It works, thanks!
