### ISSUE TITLE
Remote notification doesn't has badge information

### ISSUE THREAD

**Issue by leonovvalentin** [dimelo/Dimelo-iOS#19]
Hello!

It seems that server doesn't send information about badge in a remote notification.
I see `badge: (null)` in a notification description.

Would you describe this moment?

**Comment by jarthod** [comment]
Hello!

It does unless this is disabled from the Dimelo Digital source options. This is for when the host app uses the badge for other things and wants to keep it in control. Do you have access to source configuration? can you check if the options is on or off?

**Comment by edouardracimora** [comment]
Hello
I work at Direct Energie and can access to Dimelo Digital source options. 
I have unticked the source configuration for "Désactiver les badges APN" (see attached)
![source_dimelo_app](https://user-images.githubusercontent.com/36261607/35965785-424021b8-0cbc-11e8-885e-71081615bb95.PNG)

Can you confirm it ok ?

thanks
Edouard

**Comment by DrissTM** [comment]
Hi Edouard,

Yes, this is the checkbox @jarthod was talking about, now you should receive badge information in your notifications.

Let me know if you need more assistance.

**Comment by leonovvalentin** [comment]
Thanks for your explanation! Problem was solved.
