### ISSUE TITLE
Dimelo.sharedInstance().sdkVersion retourne une mauvaise valeur

### ISSUE THREAD

**Issue by sdc-78** [dimelo/Dimelo-iOS#21]
Dimelo.sharedInstance().sdkVersion retourne "1.7.6" alors que j'utilise la version 1.7.7 du SDK.

**Comment by waelba** [comment]
Hi @sdc-78 ,
It's fixed in `v1.7.8`
Thanks

**Comment by sdc-78** [comment]
@waelbenabdallah Good.
