### ISSUE TITLE
Dimelo n'est pas compatible "bitcode"

### ISSUE THREAD

**Issue by sdc-78** [dimelo/Dimelo-iOS#22]
Lorsque j'essaie de construire une archive de mon application, qui utilise le pod Dimelo, alors que le paramètre `ENABLE_BITCODE` est activé, j'obtiens l'erreur suivante :

`ld: bitcode bundle could not be generated because '.../Pods/Dimelo-iOS/Dimelo.framework/Dimelo' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '.../Pods/Dimelo-iOS/Dimelo.framework/Dimelo' for architecture arm64.`

Si je supprime Dimelo de mon application ou que je désactive le paramètre `ENABLE_BITCODE`, cela fonctionne.

Est-ce qu'il serait possible d'obtenir une version du SDK Dimelo compatible bitcode ?

**Comment by waelba** [comment]
Hi @sdc-78 ,

This will be fixed in the next release (v1.7.8)
Thanks

**Comment by odemolliens** [comment]
Same here, still waiting a fix

**Comment by waelba** [comment]
Hi @sdc-78, @odemolliens,
It's fixed in `v1.7.8`
Thanks

**Comment by sdc-78** [comment]
@waelbenabdallah It works. Thanks.
