### ISSUE TITLE
probleme de textField avec Menu

### ISSUE THREAD

**Issue by InesBokri** [dimelo/Dimelo-iOS#25]
Bonjour,

Y a une anomalie, c'est que le clavier de Dimelo ne se cache pas lorsque j'ouvre un Menu. Je vous communique ci-joint 2 screen shot afin de comprendre la problématique. Cette anomalie est trés genante surtout lorsque le clavier est ouvert.

Je compte sur votre réactivité habituelle.

Bien cordialement,
Ines,
![img_0954](https://user-images.githubusercontent.com/28629975/39234961-f75b6d02-4874-11e8-88ab-f42ff4a72334.PNG)
![img_0955](https://user-images.githubusercontent.com/28629975/39234968-fa0e682e-4874-11e8-9f65-6318ff29f3ab.PNG)

**Comment by waelba** [comment]
Bonjour, 
C'est le comportement normal vue que le Dimelo Chat est encore instancié en background et vue que vous avez intégré notre Chat comme un ChildViewController, vous pouvez fermer le clavier à l'ouverture de `Drawer` en utilisant `view.endEditing(true)`
