### ISSUE TITLE
Changer "send" par "envoyer"

### ISSUE THREAD

**Issue by InesBokri** [dimelo/Dimelo-iOS#27]
Bonjour,

Je veux changer le button "send" du clavier par "envoyer".

Merci pour votre réactivité surtout pour @waelbenabdallah

**Comment by waelba** [comment]
Bonjour,

C'est le cas déjà en choisissant le français comme langue du téléphone par défaut. si vous voulez le forcer, vous pouvez créer un fichier de localisation `DimeloLocalizable.strings` puis utilisez la clé `"dimeloSendButtonTitle" = "Envoyer";`

**Comment by InesBokri** [comment]
J'ai ajouté DimeloLocalizable.strings dans le projet et j'ai ajouté cette ligne "dimeloSendButtonTitle" = "Envoyer"; dans le fichier mais ca marche pas. Toujours je trouve "send"

**Comment by waelba** [comment]
tu as ajouté la langue française dans ton projet avant tout ?

![capture d ecran](https://user-images.githubusercontent.com/6080628/41402599-02b2b9ec-6fc3-11e8-94c6-e95707450d4b.png)

**Comment by InesBokri** [comment]
Tu veux dire dans DimeloConfig.plit? Oui language = fr

**Comment by waelba** [comment]
Tu peux m'envoyer une capture d'écran de la structure de projet?

**Comment by InesBokri** [comment]
![image](https://user-images.githubusercontent.com/28629975/41402849-abe353dc-6fc3-11e8-9873-19044a6af34f.png)

**Comment by InesBokri** [comment]
C'est bon cette imprim ecran

**Comment by InesBokri** [comment]
C'est bonnnnn Merci wael!
Par contre j'ai un autre bug
