### ISSUE TITLE
Problem with Keyboard when Switching the Language .

### ISSUE THREAD

**Issue by AhmedShammala** [dimelo/Dimelo-iOS#29]
there is a space appeared above the keyboard when we switching the language as you can see in this screenshot , any help ?

Thanks

<img width="371" alt="screen shot 2018-06-27 at 2 33 15 pm" src="https://user-images.githubusercontent.com/11911318/41971482-4217de38-7a17-11e8-931b-2928ec9b1d3c.png">

**Comment by waelba** [comment]
Hi @AhmedShammala ,

could you say us which version of our SDK do you use ?

Regards.

**Comment by AhmedShammala** [comment]
Hi @waelbenabdallah  the last one  1.7.9

**Comment by waelba** [comment]
Hi @AhmedShammala,

Thanks for your response, can you reproduce this problem in our sampleApp because I cannot reproduce it otherwise can you send me a sample app with the same problem

Thanks,

**Comment by AhmedShammala** [comment]
@waelbenabdallah it's have a conflict with this library "IQKeyboardManager" cause this bad behavior
