### ISSUE TITLE
Linking fails on build for Simulator

### ISSUE THREAD

**Issue by kei-sidorov** [dimelo/Dimelo-iOS#30]
After update to v.1.8.0 linking fails with message:
```
ld: warning: ignoring file projectpath/Pods/Dimelo-iOS/Dimelo.framework/Dimelo
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Dimelo", referenced from:
      l_protocol_conformances in Dimelo+ContactChatServiceProtocol.o
      objc-class-ref in DimeloChatService.o
      objc-class-ref in ContactChatViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by waelba** [comment]
Hello @kei-sidorov,

It's a Cocoapods bug, remove your pods, clean derived data then replace this on .podfile.
`pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS'`

**Comment by kei-sidorov** [comment]
Hello!
It doesn't helps. In Podfile: `pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS.git', :commit => '9519db9'`
And I tried to clean Derived data folder before open this issue. Tried clean again -- still not compile.

**Comment by waelba** [comment]
Hello! 
Can you test only with `pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS.git'` ?

**Comment by waelba** [comment]
Hello @kei-sidorov!, 
You still have the problem ?

**Comment by sdc-78** [comment]
Hello!
I have the same problem.
It seems you did not include binaries for x86_64 architecture.
It seems to be the same problem as https://github.com/dimelo/Dimelo-iOS/issues/13.

**Comment by DrissTM** [comment]
Hi @sdc-78,

Which installation method are you trying to use ? CocoaPods or Framework ?

**Comment by sdc-78** [comment]
Hi,

I use CocoaPods.

**Comment by DrissTM** [comment]
Can you provide with these informations:
- Which Xcode version are you running ?
- Which version of Dimelo are you trying to compile with ?
- Can you also provide with a screenshot of your build settings ?

**Comment by waelba** [comment]
Hi @sdc-78, 
Can you test this:
* clean cocoapods cache
`pod cache clean --all`
* remove `Podfile.lock`
* add this line to your **Podfile**
`pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS', :tag => 'v1.8.0'`
* run `pod install` command
