### ISSUE TITLE
Compiler Warning

### ISSUE THREAD

**Issue by leonovvalentin** [dimelo/Dimelo-iOS#31]
When project is compiled I see the warning:

> umbrella header for module 'Dimelo' does not include header 'DimeloChatInputAccessoryView.h':
> #import "Headers/Dimelo.h"
> ^

Am I right understand that it is Dimelo-iOS framework problem? Could you fix it?

**Comment by waelba** [comment]
Hi @leonovvalentin ,

Thanks for reporting the issue. It will be fixed in the next version.

Best

**Comment by waelba** [comment]
Hi @leonovvalentin  ,
It's fixed in `v1.9.1`
Thanks
