### ISSUE TITLE
Crash when click on "OK" button to close the chat view controller

### ISSUE THREAD

**Issue by ludriv** [dimelo/Dimelo-iOS#32]
Hello,

When I click on "OK" button to dismiss the chat view controller (from a push notification or by presenting manually) using `dimelo.displayChatView()` without setting the `dimelo.delegate` (delegate is `nil`) my app crashes.

I'm using the last version: `1.9.1`

**Comment by waelba** [comment]
Hello @ludriv ,

You should setting the `dimelo.delegate = self` and overriding `- (void) dimeloDisplayChatViewController:(Dimelo*)dimelo`

**Comment by ludriv** [comment]
@waelbenabdallah thank you for replying me so fast. 
So there is no other way to _just_ display the chat view controller (and close it) without implement the delegate?

**Comment by waelba** [comment]
@ludriv not for the moment maybe in the next releases :)
