### ISSUE TITLE
chatViewController() weird behavior

### ISSUE THREAD

**Issue by tylerlong** [dimelo/Dimelo-iOS#34]
![image](https://user-images.githubusercontent.com/733544/62255422-f99e5f80-b3b1-11e9-9c2a-2c24b6994c2f.png)

So the `dimelo.chatViewController()` view controller is not like other view controrller. It "jumps" out of its container.

Each tab content should be child of the tab bar. But this chat view overlaps the tab bar menu. I think it is caused by some auto layout settings.

**Comment by waelba** [comment]
Hi @tylerlong ,
It's fixed in `v1.9.3`
Thanks
