### ISSUE TITLE
back button is not visible

### ISSUE THREAD

**Issue by tosuccesspractice** [dimelo/Dimelo-iOS#38]
I integrate sdk 1.9.5 but when i show viewcontroller Dimelo i don't have back button here is a screen witch show what i m having 

to show Dimelo Chat i'm doing something like that :

      static func showDimeloChat(containerView: UIView) {
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        if let dimelo = appDelegate?.dimelo {
            if let vc = dimelo.chatViewController() {
                containerView.addSubview(vc.view)
            }
        }
      }

<img width="485" alt="Capture d'écran 2020-06-14 21 39 58" src="https://user-images.githubusercontent.com/60525893/84602464-f60bae00-ae87-11ea-92f5-6b448a68c131.png">

**Comment by waelba** [comment]
Hi @tosuccesspractice,
You need to add `rightBarButtonItem` to your `navigationItem` by implementing `dimeloDisplayChatViewController:` method. You can follow our example in github [here](https://github.com/ringcentral-tutorials/engage-digital-messaging-ios-demo/blob/master/CocoaPods%20Install/DimeloSampleApp/DimeloTestAppDelegate.m#L139).

**Comment by tosuccesspractice** [comment]
hi @wa-el 

I try this but i don't in function dimeloDisplayChatViewController 

i enter in function like dimeloDidEndNetworkActivity but not in dimeloDisplayChatViewController


      func initView() {
       let dimelo = PartNavigator.showDimeloChat(containerView: self.containerDimelo)
       
       dimelo.delegate = self
        
    }



    func dimeloDisplayChatViewController(_ dimelo: Dimelo!) {
        let dimeloViewController = dimelo.chatViewController()
        let menu_button_ = UIBarButtonItem(image: UIImage(named: "menu"),
                                           style: UIBarButtonItem.Style.plain ,
            target: self, action: "OnMenuClicked:")
        dimeloViewController?.navigationItem.rightBarButtonItem = menu_button_
        dimeloViewController?.title = "zz"
        dimeloViewController?.navigationController?.title = "zzsdfd"
        
        dimeloViewController?.navigationItem.backBarButtonItem = menu_button_
    }
    
    func dimeloDidEndNetworkActivity(_ dimelo: Dimelo!) {
        
    }
    func dimeloDidBeginNetworkActivity(_ dimelo: Dimelo!) {
        
    }
    func dimeloChatWillAppear(_ notification: Notification!) {
        
    }
    func dimeloChatDidAppear(_ notification: Notification!) {
    
    }
    func dimeloUnreadCountDidChange(_ notification: Notification!) {
        
    }
    func dimeloChatDidDisappear(_ notification: Notification!) {
        
    }
    func dimeloChatWillDisappear(_ notification: Notification!) {
        
    }
    func dimeloChatDidSendMessage(_ notification: Notification!) {
        
    }
    func dimeloWelcomeMessageDidChange(_ notification: Notification!) {
        
    }
    func dimeloChatDidReceiveNewMessages(_ notification: Notification!) {
        
    }


the function dimeloDisplayChatViewController is not called others functions of delegate dimeloDidEndNetworkActivity and dimeloDidBeginNetworkActivity are called
