### ISSUE TITLE
didReceiveRemoteNotification not called

### ISSUE THREAD

**Issue by tosuccesspractice** [dimelo/Dimelo-iOS#39]
i send notification i receive it on the phone no problem 

now i want to customise image title ...

the problem is this function on delegate was never called didReceiveRemoteNotification

On appDelegate didFinishLaunchingWithOptions : 

                // Dimelo: Push Notif and Badge
        dimelo?.updateAppBadgeNumber = true
        dimelo?.developmentAPNS = true
        dimelo?.initialize(withApiSecret: BuildConfig.GetInstance().getDimeloApiSecret(), domainName: BuildConfig.GetInstance().getDimeloDomainName(), delegate: self)

         func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        // Register the device token.
        Dimelo.sharedInstance().deviceToken = deviceToken
    }
    
    func dimeloDidBeginNetworkActivity(_ dimelo: Dimelo?) {
        UIApplication.shared.isNetworkActivityIndicatorVisible = true
    }
    
    func dimeloDidEndNetworkActivity(_ dimelo: Dimelo?) {
        UIApplication.shared.isNetworkActivityIndicatorVisible = false
    }
    
    func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        dimelo?.consumeReceivedRemoteNotification(userInfo)
    }

I already activate remote notification on baclground mode 

but the function didReceiveRemoteNotification was never called :(

**Comment by tosuccesspractice** [comment]
When i see error detail on xcode log when receive notification i have : 
Only notification trigged by our SERVER/SDK are handled by Accengage.

**Comment by tosuccesspractice** [comment]
i use 

        func dimelo(_ dimelo: Dimelo!, shouldDisplayNotificationWithText message: String!) -> Bool {
        return false
    }

but this function never called

**Comment by tosuccesspractice** [comment]
why nobody respond ? it's really urgent problem ?

**Comment by waelba** [comment]
Hi @tosuccesspractice,

I will check this and I will back to you as soon as possible.

Regard,

**Comment by tosuccesspractice** [comment]
how many times ? because it's really problematic for me :( i already lost a lot of time because of this problem

i never get inside this function shouldDisplayNotificationWithText

**Comment by Bacdol** [comment]
Hi, can you say me for which customer do you integration our mobile SDK ? Thanks to it we can route you to the good person for support, regards.

**Comment by tosuccesspractice** [comment]
it's for Engie

**Comment by Bacdol** [comment]
We do not have any in progress mobile integration project with Engie for the moment, if you need support on existing mobile integration you need to contact our support team by email (support.engagedigital@ringcentral.com) to be redirection to a technical resources.

**Comment by DrissTM** [comment]
I'm closing this issue. Don't hesitate to re-open or create a new one if needed.

Regards,
Driss.
