### ISSUE TITLE
Je reçois Dimelo même avec des autres notifications hors messagerie

### ISSUE THREAD

**Issue by devzhr** [dimelo/Dimelo-iOS#40]
Bonjour,
j'ai fait une mise à ajour a la version 1.9.5 et j'ai changé mon code vers :
```swift
dimelo = Dimelo.sharedInstance()
dimelo.initialize(withApiSecret: apiSecret, domainName: "mondomaine", delegate: dimeloDelegate)
```
et avec la 1.9.2 étais bien marcher :
```swift
dimelo = Dimelo(apiSecret: apiSecret, domainName: "mondomaine", delegate: dimeloDelegate)
```

Pourquoi il affiche dimelo tout le temps meme si une notification hors messagerie ?

**Comment by DrissTM** [comment]
Bonjour @devzhr,

C'est un bug qui est en train d'être corrigé par notre équipe.

Nous vous informerons dès qu'une nouvelle version comprenant le fix aura été release.


Cordialement,
Driss.

**Comment by devzhr** [comment]
Pour info le bug a partir de 1.9.3

**Comment by DrissTM** [comment]
Bonjour @devzhr,

Nous venons de release la version **2.1.0** qui devrait corriger ce bug.

Veuillez noter que d'importantes modifications ont été apportées à la gestion des notifications par le SDK et que certains changements seront nécessaires du coté de votre application pour faire fonctionner les notifications du SDK (tout est décrit dans [cette documentation](https://github.com/ringcentral/engage-digital-messaging-ios/blob/master/Notifications.md)).

N'hésitez pas à rouvrir cette issue ou à en créer une autre si besoin.


Cordialement,
Driss.
