### ISSUE TITLE
Open Chat Window when clicking on notification

### ISSUE THREAD

**Issue by gbaccetta** [dimelo/Dimelo-iOS#42]
Hello, when letting the SDK manage the notification, when user click on a push notification, the app is opened but the user isn't redirected automatically to the dimelo page. Since it's the sdk that manage the push notification how can we set a deeplink (or similar) to open the dimelo chat window ?

**Comment by DrissTM** [comment]
Hi @gbaccetta,

What version of the SDK are you currently using ?

**Comment by gbaccetta** [comment]
Hi there,

Thanks for your fast reply. I'm using the last one normally. 2.1.1

**Comment by DrissTM** [comment]
Did you follow the new instructions regarding [push notification handling](https://github.com/ringcentral/engage-digital-messaging-ios/blob/master/Notifications.md). There was a lot of changes in version 2.1.0.

If you followed everything in this document would you be able to share a snippet of the problematic piece(s) of code ?

Oh also, I may have misunderstood your issue, the push notification the user is clicking on: is it a notification triggered by a message coming from Engage Digital or is it a custom notification triggered by yourself ?
