### ISSUE TITLE
[Dimelo sharedInstance].unreadCount can't be obtained when the app starts

### ISSUE THREAD

**Issue by GD-PeaceMinusone** [dimelo/Dimelo-iOS#43]
As the title says, but I put the app in the background, and when I go back to the foreground, it's immediately can be obtained in this method : **applicationWillEnterForeground**, Please help me with this question, thank you !

**Comment by GD-PeaceMinusone** [comment]
One caveat: In the middle of this, no other code is executed, and you can just get the unreadCount when from the background back to the foreground

**Comment by waelba** [comment]
Hi @GD-PeaceMinusone ,

You can use the same logic as the sampleApp to get the unread count (see `updateUnreadCount` function).

Regard,
