### ISSUE TITLE
Does it support structured messages?

### ISSUE THREAD

**Issue by tylerlong** [dimelo/Dimelo-iOS#44]
Ref: https://developers.ringcentral.com/engage/digital/guide/interactions/structured-messages/quick-start

Link about is the web page. I am wondering does iOS support the same feature? If yes, how to enable it from programming perspective?

**Comment by CedricBm** [comment]
Hello, Yes iOS supports structured messages. You just need to have at least the v2.0.0 version.

> Feature: support the structured messages (quick reply, template, carousel and rich link)

cf https://github.com/ringcentral/engage-digital-messaging-ios/blob/master/CHANGELOG.md#dimelo-ios-sdk-200-july-21th-2020

You can also see it here https://developers.ringcentral.com/engage/digital/guide/interactions/structured-messages in the table that iOS supports structured messages. (Android also supports them, the documentation will be updated)
