### ISSUE TITLE
No ARM Simulator support

### ISSUE THREAD

**Issue by sparklone** [dimelo/Dimelo-iOS#46]
Hello!

Could you please provide support for the ARM Simulator that is available on M1 Macs? Now, as I can see library doesn't support arm64 for a simulator, only i386, x86_64.
https://github.com/ringcentral/engage-digital-messaging-ios/blob/master/Dimelo.xcframework/Info.plist

**Comment by lenkaiser** [comment]
Could you provide an ETA when we can expect this?

**Comment by DrissTM** [comment]
Hi,

At the moment adding support for arm simulator would break support for x86_64 simulator and that's a trade-off we cannot afford at the moment as x86_64 is the platform we're using internally.

We're waiting for Apple to fix this issue so that we can support both platforms. We'll keep you informed as soon as a solution is available.

**Comment by lenkaiser** [comment]
Thank you for the quick reply, we now know we're not waiting for "nothing". Do you have a link for the issue tracker of Apple?

**Comment by DrissTM** [comment]
I'm not sure the issue is tracked on Apple side, but here's a [link to a Apple developer thread](https://developer.apple.com/forums/thread/666335?answerId=662473022#662473022)

**Comment by lenkaiser** [comment]
Any updates on this issue? As there hasn't been any responses on the developer thread for 3 months and isn't actively monitored by Apple.

**Comment by lenkaiser** [comment]
@DrissTM GeoffKnows has responded to this thread. Can you take a look at his comment and let us know if this fixes your issue?
https://developer.apple.com/forums/thread/666335?answerId=707645022#707645022

**Comment by DrissTM** [comment]
hi @lenkaiser, thanks for the heads up! We're going to try this and I'll keep you informed on whether it fixes the issue or not

**Comment by waelba** [comment]
Hi,

We have fixed the issue in the new SDK release version (`v2.4.4`).

Regards,

**Comment by lenkaiser** [comment]
@waelba So far it seems to work! This ticket can be closed, I'll re-open the ticket if any problems do occur.
