### ISSUE TITLE
The placeholder in the text field is truncated

### ISSUE THREAD

**Issue by idrisAd** [dimelo/Dimelo-iOS#50]
Hello,

As you can see on screenshoot the placeholder is truncated when we open the chat.

Config:
iPhone 14 Pro
iOS 17.1.1
SDK: Dimelo-iOS v2.4.3

![IMG_3316 - Moyenne](https://github.com/ringcentral/engage-digital-messaging-ios/assets/32459686/814b139f-6835-4020-8585-d147bb28af44)

Thanks for all the help on the subject

**Comment by waelba** [comment]
Hi @idrisAd ,
Can you check this issue using the last SDK version (v2.6.3).
Regard,
WAel

**Comment by idrisAd** [comment]
Hi @waelba ,
After update to 2.6.3 it's OK
![IMG_3317 - Moyenne](https://github.com/ringcentral/engage-digital-messaging-ios/assets/32459686/db1907a4-d5f0-4eec-be35-ac7afbd1e007)

Thanks

**Comment by idrisAd** [comment]
It's OK with the new version
