### ISSUE TITLE
Crash when click on "Add attachment" button

### ISSUE THREAD

**Issue by avezier** [dimelo/Dimelo-iOS#9]
Hello,

I have integrated Dimelo 1.5.0 library in a Swift project.
Everything is working fine but when I click on "Add Attachment" button from the Dimelo chat view, the app crashes. I have no information from the debugger that could help me finding the cause.

Regards

**Comment by jarthod** [comment]
Hello again, as advised in your other issue, could you please upgrade to the latest version and confirm if this issue is still present? a few things changed on this part of the code in between.

**Comment by jarthod** [comment]
In the meanwhile could you at least provide us with the exception and stacktrace so we can have a look?
BTW if you're using swift, since Dimelo Mobile 1.7.0 we provide a [Dimelo.framework](https://github.com/dimelo/Dimelo-iOS#how-to-install-manually) package which is way easier to integrate.

**Comment by jarthod** [comment]
Without any response I'm closing this, please reopen if you have new details.
